name: Main

on:
  push: { branches: ["main"] }
  workflow_dispatch: # Can run manually from the Actions tab

permissions: {}

jobs:
  ci:
    name: "CI"
    uses: git-lfs-hub/ci-cd/.github/workflows/ci.yml@main
    secrets: inherit

  cd:
    name: "CD"
    needs: ci
    uses: git-lfs-hub/ci-cd/.github/workflows/cd.yml@main
    secrets: inherit

  e2e:
    name: "E2E"
    needs: cd
    if: ${{ vars.GLH_TEST_REPO != '' }}
    uses: git-lfs-hub/ci-cd/.github/workflows/e2e.yml@main
    with:
      test-repo: ${{ vars.GLH_TEST_REPO }}
    secrets: inherit
    permissions: { contents: write }
