name: Main

on:
  push: { branches: ["main"] }
  workflow_dispatch: # Can run manually from the Actions tab

permissions: {}

jobs:
  ci:
    name: "CI"
    uses: git-lfs-hub/ci-cd/.github/workflows/ci.yml@main
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

  cd:
    name: "CD"
    needs: ci
    uses: git-lfs-hub/ci-cd/.github/workflows/cd.yml@main
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  e2e:
    name: "E2E"
    needs: cd
    if: ${{ vars.GLH_TEST_REPO != '' }}
    uses: git-lfs-hub/ci-cd/.github/workflows/e2e.yml@main
    with:
      test-repo: ${{ vars.GLH_TEST_REPO }}
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      GLH_STAGING_GITHUB_PAT: ${{ secrets.GLH_STAGING_GITHUB_PAT }}
      GLH_LOGIN_SECRET: ${{ secrets.GLH_LOGIN_SECRET }}
    permissions: { contents: write }
