name: Main

on:
  push:
    branches: ["main"]

  workflow_dispatch: # Can run this workflow manually from the Actions tab

env:
  GLH_VARS_JSON: ${{ vars.GLH_VARS_JSON || secrets.GLH_VARS_JSON }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM || secrets.TURBO_TEAM }}
  TURBO_TEAMID: ${{ vars.TURBO_TEAMID || secrets.TURBO_TEAMID }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: ./.github/actions/init

      - run: bunx turbo run test build

      - run: bunx turbo run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Turbo Summary
        uses: ./.github/actions/turbo-summary

  smoke:
    name: "Smoke"
    needs: deploy
    runs-on: ubuntu-latest
    concurrency:
      group: lfs-server-prod-smoke
      cancel-in-progress: false
    env:
      GH_PAT: ${{ secrets.GLH_STAGING_GITHUB_PAT }}
      LOGIN_SECRET: ${{ secrets.GLH_LOGIN_SECRET }}
      PR_NUMBER: main
      RUN_ID: ${{ github.run_id }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: ./.github/actions/init

      - run: bun --bun run e2e-test
        working-directory: e2e
