name: PR

on:
  pull_request:
  workflow_dispatch: # Can run manually from the Actions tab

permissions: {}

jobs:
  ci:
    name: "CI"
    uses: git-lfs-hub/ci-cd/.github/workflows/ci.yml@main
    secrets: inherit

  staging:
    name: "Staging"
    if: github.event.pull_request.head.repo.full_name == github.repository
    uses: git-lfs-hub/ci-cd/.github/workflows/staging.yml@main
    with:
      test-repo: ${{ vars.GLH_E2E_TEST_REPO }}
    secrets: inherit
    permissions: { contents: write }

  can-merge:
    name: Can merge
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: git-lfs-hub/ci-cd/actions/check-can-merge@main
