name: Upstream

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  upstream:
    name: "Upstream"
    if: vars.GLH_UPSTREAM == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: scripts/upstream.sh pre-commit
        shell: bash
